### ISSUE TITLE
Cards with recipe

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#1]
##  Value statement

As a **user** 
I need **the cards with recipe** 
so that **I can choose the recipe that I want to cook.**

##  Description

![RecipeCards](https://user-images.githubusercontent.com/77296952/112010469-a0a3b200-8b27-11eb-92b8-f4df0ffd0c9e.png)

##  Acceptance criteria

- [x] RecipeCards with image of the dish and count of calories per serving and ingredients are always visible.

## Tasks

- [x] Create feature branch
- [x] Fetch data from API
- [x] Create RecipeCard component in Storybook
- [x] Write component tests
- [x] Add new propTypes
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

middle
