### ISSUE TITLE
Saved Page

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#11]
## Value statement

As **a user** I want **to see the saved recipes** so that **I can better find my favourite recipes.**

## Description

![SavedRecipes](https://user-images.githubusercontent.com/77296952/112046265-1883d380-8b4c-11eb-82f3-d568dec4ee53.png)

## Acceptance criteria

- [x] Show saved recipes by click on link Saved in Header.
- [x] Recipe cards with image, recipe title, count of calories per serving, ingredients and delete button are shown.
- [x] At click on delete button recipe will be deleted from saved page and local storage. 
- [x] Header includes All link.
- [x] Return to homepage by click on link All.

## Tasks

- [x] Create feature branch
- [x] Create saved recipes in Storybook
- [x] Write component tests
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

middle
