### ISSUE TITLE
Rating and comment form

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#12]
## Value statement

As **a user** I want **to leave rating and comment** so that **I can see which recipe is more suitable for me.**

## Description

![RatingandCommentForm](https://user-images.githubusercontent.com/77296952/112056626-8504cf80-8b58-11eb-8302-d9913ebb13e8.png)

## Acceptance criteria

- [x] Has 5 stars without fill, input field, texture and submit button.
- [x] On submit will be called with count of stars, name and text of comment. 
- [x] After submit rating, name and comment text will be shown on the bottom of detail page.
- [x] User can edit leaved comment.

## Tasks

- [x] Create feature branch
- [x] Create Rating form in Storybook
- [x] Write component tests
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

middle
