### ISSUE TITLE
Searchinput

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#2]
## Value statement

As **a user** I want **to search
for recipe by using of ingredient name** so that **I can choose the suitable recipe.**

## Description

![SearchBar](https://user-images.githubusercontent.com/77296952/112009964-25da9700-8b27-11eb-8615-c2a939e1478b.png)

## Acceptance criteria

- [x] The input reacts on submit(Enter key).
- [x] The Recipes that include the ingredient from search input will be shown.
- [x] If the input field is not filled bei submit user gets alert "Please fill the Search Bar".
- [x] If the input field is filled with not existing ingredient user gets alert "Cannot find such recipe".
- [x] The input is not cleared after submit.

## Tasks

- [x] Create feature branch
- [x] Create search bar component in Storybook
- [x] Create alert component in Storybook
- [x] Write components tests
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

middle
