### ISSUE TITLE
Recipe Filter

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#3]
## Value statement

As **a user** I want **to filter recipes
by calories, diet, allergy restrictions or cuisine types** so that **I can choose the suitable recipe.**

## Description

![AllRecipes](https://user-images.githubusercontent.com/77296952/112053736-fcd0fb00-8b54-11eb-8ecb-5ea67aac6230.png)

## Acceptance criteria

- [x] Bei click on refine your search button the filter form will be shown.
- [x] If entered value of calories in input fields for calories is not a number user get alert "Your calories input is not valid".
- [x] If entered value of calories in input field To less then entered value of calories in input field From user get alert "Your calories input is not valid".
- [x] The checkboxes react on click(will be checked).
- [x] Bei double click a checkbox will be unchecked.
- [x] User can choose multiply checkboxes.
- [x] Bei click on find button the filtered Recipes will be shown and filter form will be hidden.
- [x] If no recipe with such filter combination can be found user get alert "Cannot find such recipe".
- [x] Bei click on clear button all checkboxes, alerts and input fields will be cleared.
- [x] Header includes Saved link.

## Tasks

- [x] Create feature branch
- [x] Create filter form component in Storybook
- [x] Write component tests
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

high
