### ISSUE TITLE
Recipe Detail Page

### ISSUE THREAD

**Issue by AnastasiyaVasileuskaya** [AnastasiyaVasileuskaya/capstone-project#8]
## Value statement

As **a user** I want **to see details of recipe** so that **I can see the ingredients and nutritions of recipe.**

## Description

![DetailPage](https://user-images.githubusercontent.com/77296952/112026493-8f15d680-8b36-11eb-96d2-0168ca1f9947.png)

## Acceptance criteria

- [x] Show detail page by click on recipe.
- [x] Label, image, count of calories and servings, ingredients, nutritions and buttons save recipe and instructions of clicked recipe are shown.
- [x] At click on button Save recipe the recipe will be saved in local storage and button becomes text "Recipe saved" and lightgrey color. 
- [x] At click on button Instructions user will be navigate at external Webseite with full recipe instruction.
- [x] Header includes two links: all and saved.
- [x] Return to homepage by click on link All.

## Tasks

- [x] Create feature branch
- [x] Implement the using of local storage
- [x] Add React Router
- [x] Create Recipe Detail Page in Storybook
- [x] Write component tests
- [x] Add components to app(feature implementation with state)
- [x] Add missing styles

## Complexity

heigh
